### ISSUE TITLE
autism

### ISSUE THREAD

**Issue by cxdy** [LandenStephenss/Magikarp#2]
```
autism ô′tĭz″əm►
n.	A pervasive developmental disorder characterized by severe deficits in social interaction and communication, by an extremely limited range of activities and interests, and often by the presence of repetitive, stereotyped behaviors.
n.	a mental disorder characterized by inability to engage in normal social interactions and intense self-absorption, and usually accompanied by other symptoms such as language dysfunctions and repetitive behavior.
n.	behavior showing an abnormal level of absorption with one's own thoughts and disregard for external realities.
```
![](https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/61565097_10205950135108023_52216992614055936_o.jpg?_nc_cat=111&ccb=2&_nc_sid=09cbfe&_nc_ohc=-XqQ4JikT1EAX9z5tQ7&_nc_ht=scontent-lga3-1.xx&oh=c76898af711ce062fb0ae0c19852353d&oe=6018FB2F)

**Comment by cxdy** [comment]
I like how the configuration json files aren't included in the repo, just so @TravenDev can't accidentally commit his Discord API Key again

**Comment by LandenStephenss** [comment]
Can we not open garbage issues. kthx.
